# Change these first
owner: cookie-org # Your GitHub organization or username, where this repository lives
repo: web-uptime # The name of this repository

sites:
  - name: DSMR AH
    url: $DSMR_AH_ENDPOINT
    headers:
      - $DSMR_AH_AUTH
    icon: https://raw.githubusercontent.com/dsmrreader/dsmr-reader/9a166c5d82d90a218fb5c2614483e1731de893ac/dsmr_frontend/static/dsmr_frontend/img/favicons/favicon-32x32.png
  - name: DSMR ECK
    url: $DSMR_ECK_ENDPOINT
    headers:
      - $DSMR_ECK_AUTH
    icon: https://raw.githubusercontent.com/dsmrreader/dsmr-reader/9a166c5d82d90a218fb5c2614483e1731de893ac/dsmr_frontend/static/dsmr_frontend/img/favicons/favicon-32x32.png
  - name: DSMR WS
    url: $DSMR_WS_ENDPOINT
    headers:
      - $DSMR_WS_AUTH
    icon: https://raw.githubusercontent.com/dsmrreader/dsmr-reader/9a166c5d82d90a218fb5c2614483e1731de893ac/dsmr_frontend/static/dsmr_frontend/img/favicons/favicon-32x32.png
  - name: Unifi Controller
    url: $UNI_ENDPOINT
    __dangerous__body_degraded_if_text_missing: '"up":true'
  - name: Vault
    url: $VAULT_ENDPOINT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.we-dev.xyz
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Hm
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

#default assignees
assignees:
  - BasWijngaarden

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
